
lane :codesigning do
  match(type: "appstore")
end

lane :appstore do
  appicon(
    appicon_devices: [:iphone],
    appicon_image_file: "./DetectLocations/Assets.xcassets/AppIcon.appiconset/DetectLocations.png",
    appicon_path: "./DetectLocations/Assets.xcassets/"
  )
  codesigning
  gym(scheme: "DetectLocations")
  deliver(force: true)
end
